# Conexión PostgreSQL
db.url=jdbc:postgresql://localhost:5432/simulacion_db
db.user=postgres
db.password=07300614

# Query para la simulación
query=SELECT 1

# Configuración de simulación
num_muestras=3000
max_reintentos=3
pool_size=10