# Conexión PostgreSQL
db.url=jdbc:postgresql://localhost:5432/visual
db.user=postgres
db.password=1509

# Query para la simulación
query=SELECT * FROM productos

# Configuración de simulación
num_muestras=5000
max_reintentos=3
pool_size=10